[tool.poetry]
name = "proteuspy"
version = "0.92.14"
description = "proteusPy - Protein Structure Analysis and Modeling Tools"
authors = ["Eric Suchanek <suchanek@mac.com>"]
license = "BSD"
readme = "README.md"
repository = "https://github.com/suchanek/proteusPy/"
homepage = "https://github.com/suchanek/proteusPy/"
documentation = "https://suchanek.github.io/proteusPy/"
keywords = ["structural biophysics", "proteus", "disulfide bonds", "RCSB"]
classifiers=[
        "Development Status :: 4 - Beta",
        "License :: OSI Approved :: BSD License",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
        "Topic :: Scientific/Engineering :: Chemistry",
        "Programming Language :: Python :: 3.11",
        ]


packages = [{include = "proteusPy"}]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.4"
kaleido = "0.2.1"
pandas = "^1.0.0"
notebook = "6.4.12"
jupyter = "^1.0.0"
jupyterlab = ">=3"
seaborn = "^0.13.2"
pillow = "^10.2.0"
tqdm = "^4.66.2"
plotly = "^5.19.0"
DateTime = "^5.4"
jupyter_bokeh = "^4.0.0"
openai = "^1.13.3"
panel = "^1.3.8"
scikit-learn = "^1.4.1.post1"
gdown = "^5.1.0"
ipykernel = "^6.29.3"
ipygany = "^0.5.0"
nodejs = "^0.1.1"
pytube = "^15.0.0"
grpcio = "^1.62.0"
pip = "^24.0"
wget = "^3.2"
vtk = "^9.3.0"
plotly-express = "^0.4.1"
trame-jupyter-extension = "^2.0.1"
jupyter-contrib-nbextensions = "^0.7.0"
ipywidgets = "^8.1.2"
imageio = {extras = ["ffmpeg"], version = "^2.34.0"}
poethepoet = "^0.25.0"
pyvista = {extras = ["trame"], version = "^0.43.3"}
biopython = {git = "https://github.com/suchanek/biopython.git"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
black = {extras = ["jupyter"], version = "^24.2.0"}
pdoc = "^14.4.0"
poethepoet = "^0.25.0"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",  # You should have a "tests" directory
]

[tool.black]
line-length = 120

[tool.poe.tasks]
_build = "poetry build"
_install = "poetry install"
_jup_install = "poe jupyter"
_clean_sdist.script = "shutil:rmtree('sdist', ignore_errors=1)"
_clean_docs.script = "shutil:rmtree('docs', ignore_errors=1)"
_jup1 = "jupyter contrib nbextension install --sys-prefix"
_jup2 = "jupyter nbextension enable --py --sys-prefix widgetsnbextension"
_jup3 = "python -m ipykernel install --user --name proteusPy --display-name 'proteusPy'"

build = ["_build"]
install = ["_install", "_jup_install"]

  [tool.poe.tasks.jupyter]
  help = "Add jupyter extensions"
  sequence = ['_jup1', '_jup2', '_jup3']

  [tool.poe.tasks.format]
  help = "Run formatting tools on the code base"
  cmd = "black ."

  [tool.poe.tasks.format-black]
  help = "Run black on the code base"
  cmd = "black ."

  [tool.poe.tasks.docs]
  help = "Build the docs with pdoc"
  cmd = "pdoc -o docs --math --logo ./logo.png ./proteusPy"
  deps = ["_clean_docs"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
