services:
  rcsb_viewer:
    build: .
    ports:
      - "5006:5006"
    restart: always
    container_name: rcsb_viewer
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_RUNNING=true
