# Use the Miniconda3 image as a base
FROM continuumio/miniconda3

# Set environment variables to prevent interactive prompts during package installations
ENV DEBIAN_FRONTEND=noninteractive \
    PATH="/opt/conda/envs/proteusPy/bin:$PATH" \
    PYVISTA_OFF_SCREEN=true

# Copy the current directory contents into the container at /app
COPY . /app

# Copy the environment.yml file first for better layer caching
COPY environment.yml /tmp/environment.yml

# Install system dependencies including libgl1, xvfb, xauth, libxrender1, and libxext6
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libgl1-mesa-glx \
        xvfb \
        xauth \
        libxrender1 \
        libxext6 && \
    rm -rf /var/lib/apt/lists/* && \
    conda env create -f /tmp/environment.yml && \
    conda clean -a -y

# Set the working directory in the container
WORKDIR /app

# Add a non-root user for enhanced security and
# change ownership of the /app directory to the non-root user and make entrypoint.sh executable
RUN useradd -m appuser && chown -R appuser:appuser /app && chmod +x /app/entrypoint.sh

# Switch to the non-root user
USER appuser

# Expose port 5006 for the Bokeh server
EXPOSE 5006

# Set the entrypoint to the entrypoint.sh script
ENTRYPOINT ["/app/entrypoint.sh"]
