name: proteusPy
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - python=3.11
  - vtk=9.2.6
  - panel
  - bokeh
  - pyvista[all]
  - nodejs
  - pip
  - pip:
    - proteusPy

