# fly.toml app configuration file generated for proteuspy on 2025-03-26T20:40:29-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'proteuspy'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 5006
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
