name: Docker Build Cloud

on:
  workflow_dispatch:
  push:
    branches:
      - master
  release:
    types: [published]
  
jobs:
  docker:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify Docker User
        run: |
          if [ -z "${{ secrets.DOCKER_USER }}" ]; then
            echo "DOCKER_USER is not set"
            exit 1
          else
            echo "DOCKER_USER is set"
          fi

      - name: Verify Docker PAT
        run: |
          if [ -z "${{ secrets.DOCKER_PAT }}" ]; then
            echo "DOCKER_PAT is not set"
            exit 1
          else
            echo "DOCKER_PAT is set"
          fi

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USER }}/rcsb_viewer
  

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          driver: docker-container

      - name: Build and push
        id: push  # Added id to reference outputs
        uses: docker/build-push-action@v6
        with:
          context: ./viewer
          file: ./viewer/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/rcsb_viewer:latest

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: docker.io/${{ secrets.DOCKER_USER }}/rcsb_viewer  # Corrected subject-name
          subject-digest: ${{ steps.push.outputs.digest }}  # Referenced digest output
          push-to-registry: true
