name: Publish Docker image to GHCR

on:
  push:
    branches:
      - 0.97.14.dev0
      - main
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./viewer
        file: ./viewer/dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/rcsb_viewer:latest

    - name: Post to GitHub Pages (optional)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "Package rcsb_viewer has been published to ghcr.io with tag ${{ github.ref_name }}"
        