name: Testing

on: 
  push:
    branches:
      - master

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Set up Python 3.12
          uses: actions/setup-python@v3
          with: 
            python-version: 3.12

        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install wheel pytest
              pip install -e .  # Install the package in development mode from the repo

        - name: Test with pytest
          run: |
            pytest -k "not test_disulfide_class_generator"
